apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multicontainer
  name: multicontainer
spec:
  containers:
  - image: busybox
    name: busybox1
    command: ["/bin/sh","-c", "echo hello; sleep 3600"]
    resources: {}
  - image: busybox
    name: busybox2
    command: ["/bin/sh", "-c", "echo hello; sleep 3600"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
