apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Mi
  storageClassName: manual
