apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    livenessProbe:
      exec: 
        command:
        - "ls"
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      httpGet: 
        path: "/"
        port: 80
    ports:
    - containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
