apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-claim
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""
  hostPath:
    path: /tmp/pv
